// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoZGO1aa-eJvDAAffbgFovRHyzEvbaoow',
    appId: '1:471928548057:web:e8070aaa0d0f57f32d6cc8',
    messagingSenderId: '471928548057',
    projectId: 'petcare-e35be',
    authDomain: 'petcare-e35be.firebaseapp.com',
    storageBucket: 'petcare-e35be.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2HzGVjlc4Sj3Ln8L2dRzXtlIZXYX9RxE',
    appId: '1:471928548057:android:1999c2a603e294942d6cc8',
    messagingSenderId: '471928548057',
    projectId: 'petcare-e35be',
    storageBucket: 'petcare-e35be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgAG3Xn6tkIHQUjW2HMB2J-Xx90e_LUTw',
    appId: '1:471928548057:ios:3f00daaaaf6119ed2d6cc8',
    messagingSenderId: '471928548057',
    projectId: 'petcare-e35be',
    storageBucket: 'petcare-e35be.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgAG3Xn6tkIHQUjW2HMB2J-Xx90e_LUTw',
    appId: '1:471928548057:ios:3f00daaaaf6119ed2d6cc8',
    messagingSenderId: '471928548057',
    projectId: 'petcare-e35be',
    storageBucket: 'petcare-e35be.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoZGO1aa-eJvDAAffbgFovRHyzEvbaoow',
    appId: '1:471928548057:web:b354d2a0b9b001802d6cc8',
    messagingSenderId: '471928548057',
    projectId: 'petcare-e35be',
    authDomain: 'petcare-e35be.firebaseapp.com',
    storageBucket: 'petcare-e35be.firebasestorage.app',
  );
}
